export enum Routes {
  SPLASH_SCREEN = "SPLASH_SCREEN",
  HOME_SCREEN = "HOME_SCREEN",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",
  TRACK_INFO = "TRACK_INFO",
  TRACKS_SCREEN = "TRACKS_SCREEN",
}

export enum Stacks {
  ROOT = "ROOT",
  HOME = "HOME",
}
