export enum Routes {
  SPLASH_SCREEN = 'SPLASH_SCREEN',
  HOME_SCREEN = 'HOME_SCREEN',
  LOGIN_SCREEN = 'LOGIN_SCREEN',
  REGISTER_SCREEN = 'REGISTER_SCREEN',
  TRACK_INFO = 'TRACK_INFO',
  TRACKS_SCREEN = 'TRACKS_SCREEN',
  TRACKS_MAP_SCREEN = 'TRACKS_MAP_SCREEN',
  TRACK_SCREEN_COGNITIVE = 'TRACK_SCREEN_COGNITIVE',
  TRACK_SCREEN_INDICATIVE = 'TRACK_SCREEN_INDICATIVE',
  TRACK_SCREEN_STATISTICS = 'TRACK_SCREEN_STATISTICS',
  WAITING_ROOM = 'WAITING_ROOM',
  PROFILE_SCREEN = 'PROFILE_SCREEN',
  SETTINGS_SCREEN = 'SETTINGS_SCREEN',
}

export enum Stacks {
  ROOT = 'ROOT',
  HOME = 'HOME',
  TRACK = 'TRACK',
}
